"""UI related constants"""

# Window settings
WINDOW_WIDTH = 900
WINDOW_HEIGHT = 800
WINDOW_PADDING = 20

# Default values
DEFAULT_KTX_DEPARTURE = "서울"
DEFAULT_KTX_ARRIVAL = "부산"
DEFAULT_SRT_DEPARTURE = "수서"
DEFAULT_SRT_ARRIVAL = "부산"

# Time settings
RETRY_DELAY_MIN = 1.0
RETRY_DELAY_MAX = 4.0
CLIENT_RESET_INTERVAL = 500

# Log settings
LOG_MIN_LINES = 8
LOG_MAX_LINES = 10