"""Initial migration: create users and cards tables

Revision ID: 0eeb39075ab1
Revises: 
Create Date: 2025-12-29 09:48:11.865341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eeb39075ab1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('card_password', sa.String(), nullable=False),
    sa.Column('card_expired_date', sa.String(), nullable=False),
    sa.Column('card_validate_number', sa.String(), nullable=False),
    sa.Column('is_corporate', sa.Boolean(), nullable=False),
    sa.Column('train_type', sa.Enum('KORAIL', 'SRT', name='traintype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('train_type', sa.Enum('KORAIL', 'SRT', name='traintype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('cards')
    # ### end Alembic commands ###
